Search.appendIndex(
    [
                {
            "fqsen": "\\cp\\admin\\Emails_List_Table",
            "name": "Emails_List_Table",
            "summary": "Class\u0020Emails_List_Table",
            "url": "../classes/cp-admin-Emails-List-Table.html"
        },                {
            "fqsen": "\\cp\\admin\\Emails_List_Table\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "CP_Emails_List_Table\u0020constructor.",
            "url": "../classes/cp-admin-Emails-List-Table.html#method___construct"
        },                {
            "fqsen": "\\cp\\admin\\Emails_List_Table\u003A\u003A__call\u0028\u0029",
            "name": "__call",
            "summary": "",
            "url": "../classes/cp-admin-Emails-List-Table.html#method___call"
        },                {
            "fqsen": "\\cp\\admin\\Emails_List_Table\u003A\u003Aprepare_items\u0028\u0029",
            "name": "prepare_items",
            "summary": "",
            "url": "../classes/cp-admin-Emails-List-Table.html#method_prepare_items"
        },                {
            "fqsen": "\\cp\\admin\\Emails_List_Table\u003A\u003Acolumn_default\u0028\u0029",
            "name": "column_default",
            "summary": "",
            "url": "../classes/cp-admin-Emails-List-Table.html#method_column_default"
        },                {
            "fqsen": "\\cp\\admin\\Emails_List_Table\u003A\u003Ano_items\u0028\u0029",
            "name": "no_items",
            "summary": "",
            "url": "../classes/cp-admin-Emails-List-Table.html#method_no_items"
        },                {
            "fqsen": "\\cp\\admin\\Emails_List_Table\u003A\u003Aset_columns\u0028\u0029",
            "name": "set_columns",
            "summary": "",
            "url": "../classes/cp-admin-Emails-List-Table.html#method_set_columns"
        },                {
            "fqsen": "\\cp\\admin\\Emails_List_Table\u003A\u003Aget_columns\u0028\u0029",
            "name": "get_columns",
            "summary": "",
            "url": "../classes/cp-admin-Emails-List-Table.html#method_get_columns"
        },                {
            "fqsen": "\\cp\\admin\\Emails_List_Table\u003A\u003Acolumn_email\u0028\u0029",
            "name": "column_email",
            "summary": "",
            "url": "../classes/cp-admin-Emails-List-Table.html#method_column_email"
        },                {
            "fqsen": "\\cp\\admin\\Emails_List_Table\u003A\u003Acolumn_recipients\u0028\u0029",
            "name": "column_recipients",
            "summary": "",
            "url": "../classes/cp-admin-Emails-List-Table.html#method_column_recipients"
        },                {
            "fqsen": "\\cp\\admin\\Emails_List_Table\u003A\u003Acolumn_configure\u0028\u0029",
            "name": "column_configure",
            "summary": "",
            "url": "../classes/cp-admin-Emails-List-Table.html#method_column_configure"
        },                {
            "fqsen": "\\cp\\admin\\Emails_List_Table\u003A\u003A\u0024no_items_message",
            "name": "no_items_message",
            "summary": "",
            "url": "../classes/cp-admin-Emails-List-Table.html#property_no_items_message"
        },                {
            "fqsen": "\\cp\\admin\\Emails_List_Table\u003A\u003A\u0024columns",
            "name": "columns",
            "summary": "",
            "url": "../classes/cp-admin-Emails-List-Table.html#property_columns"
        },                {
            "fqsen": "\\cp\\admin\\Init",
            "name": "Init",
            "summary": "Class\u0020Init",
            "url": "../classes/cp-admin-Init.html"
        },                {
            "fqsen": "\\cp\\admin\\Init\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Init\u0020constructor.",
            "url": "../classes/cp-admin-Init.html#method___construct"
        },                {
            "fqsen": "\\cp\\admin\\Init\u003A\u003Ainit_variables\u0028\u0029",
            "name": "init_variables",
            "summary": "Init\u0020admin\u0020variables",
            "url": "../classes/cp-admin-Init.html#method_init_variables"
        },                {
            "fqsen": "\\cp\\admin\\Init\u003A\u003Aincludes\u0028\u0029",
            "name": "includes",
            "summary": "All\u0020admin\u0020includes\u0020in\u0020one\u0020function",
            "url": "../classes/cp-admin-Init.html#method_includes"
        },                {
            "fqsen": "\\cp\\admin\\Init\u003A\u003A\u0024templates_path",
            "name": "templates_path",
            "summary": "",
            "url": "../classes/cp-admin-Init.html#property_templates_path"
        },                {
            "fqsen": "\\cp\\admin\\Install",
            "name": "Install",
            "summary": "Class\u0020Install",
            "url": "../classes/cp-admin-Install.html"
        },                {
            "fqsen": "\\cp\\admin\\Install\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Install\u0020constructor.",
            "url": "../classes/cp-admin-Install.html#method___construct"
        },                {
            "fqsen": "\\cp\\admin\\Install\u003A\u003Aactivation\u0028\u0029",
            "name": "activation",
            "summary": "Plugin\u0020Activation",
            "url": "../classes/cp-admin-Install.html#method_activation"
        },                {
            "fqsen": "\\cp\\admin\\Install\u003A\u003Amaybe_network_activation\u0028\u0029",
            "name": "maybe_network_activation",
            "summary": "Check\u0020if\u0020plugin\u0020is\u0020network\u0020activated\u0020make\u0020the\u0020first\u0020installation\u0020on\u0020all\u0020blogs",
            "url": "../classes/cp-admin-Install.html#method_maybe_network_activation"
        },                {
            "fqsen": "\\cp\\admin\\Install\u003A\u003Asingle_site_activation\u0028\u0029",
            "name": "single_site_activation",
            "summary": "Single\u0020site\u0020plugin\u0020activation\u0020handler",
            "url": "../classes/cp-admin-Install.html#method_single_site_activation"
        },                {
            "fqsen": "\\cp\\admin\\Install\u003A\u003Afirst_install\u0028\u0029",
            "name": "first_install",
            "summary": "Actions\u0020on\u0020the\u0020first\u0020install",
            "url": "../classes/cp-admin-Install.html#method_first_install"
        },                {
            "fqsen": "\\cp\\admin\\Install\u003A\u003Aset_defaults\u0028\u0029",
            "name": "set_defaults",
            "summary": "Set\u0020default\u0020CP\u0020settings",
            "url": "../classes/cp-admin-Install.html#method_set_defaults"
        },                {
            "fqsen": "\\cp\\admin\\Install\u003A\u003Acreate_roles\u0028\u0029",
            "name": "create_roles",
            "summary": "Parse\u0020user\u0020capabilities\u0020and\u0020set\u0020the\u0020proper\u0020capabilities\u0020for\u0020roles",
            "url": "../classes/cp-admin-Install.html#method_create_roles"
        },                {
            "fqsen": "\\cp\\admin\\Install\u003A\u003Apredefined_pages\u0028\u0029",
            "name": "predefined_pages",
            "summary": "Install\u0020all\u0020predefined\u0020pages",
            "url": "../classes/cp-admin-Install.html#method_predefined_pages"
        },                {
            "fqsen": "\\cp\\admin\\Install\u003A\u003Apredefined_page\u0028\u0029",
            "name": "predefined_page",
            "summary": "Install\u0020predefined\u0020page\u0020via\u0020the\u0020page\u0020slug",
            "url": "../classes/cp-admin-Install.html#method_predefined_page"
        },                {
            "fqsen": "\\cp\\admin\\Install\u003A\u003A\u0024install_process",
            "name": "install_process",
            "summary": "",
            "url": "../classes/cp-admin-Install.html#property_install_process"
        },                {
            "fqsen": "\\cp\\ajax\\Init",
            "name": "Init",
            "summary": "Class\u0020Init",
            "url": "../classes/cp-ajax-Init.html"
        },                {
            "fqsen": "\\cp\\ajax\\Init\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Init\u0020constructor.",
            "url": "../classes/cp-ajax-Init.html#method___construct"
        },                {
            "fqsen": "\\cp\\ajax\\Init\u003A\u003Aincludes\u0028\u0029",
            "name": "includes",
            "summary": "All\u0020AJAX\u0020includes",
            "url": "../classes/cp-ajax-Init.html#method_includes"
        },                {
            "fqsen": "\\cp\\ajax\\Init\u003A\u003Acheck_nonce\u0028\u0029",
            "name": "check_nonce",
            "summary": "Check\u0020nonce",
            "url": "../classes/cp-ajax-Init.html#method_check_nonce"
        },                {
            "fqsen": "\\cp\\Config",
            "name": "Config",
            "summary": "Class\u0020Config",
            "url": "../classes/cp-Config.html"
        },                {
            "fqsen": "\\cp\\Config\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Config\u0020constructor.",
            "url": "../classes/cp-Config.html#method___construct"
        },                {
            "fqsen": "\\cp\\Config\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Get\u0020variable\u0020from\u0020config",
            "url": "../classes/cp-Config.html#method_get"
        },                {
            "fqsen": "\\cp\\Config\u003A\u003Ainit_defaults\u0028\u0029",
            "name": "init_defaults",
            "summary": "Init\u0020plugin\u0020defaults",
            "url": "../classes/cp-Config.html#method_init_defaults"
        },                {
            "fqsen": "\\cp\\Config\u003A\u003Ainit_custom_roles\u0028\u0029",
            "name": "init_custom_roles",
            "summary": "Initialize\u0020CP\u0020custom\u0020roles\u0020list",
            "url": "../classes/cp-Config.html#method_init_custom_roles"
        },                {
            "fqsen": "\\cp\\Config\u003A\u003Ainit_capabilities_map\u0028\u0029",
            "name": "init_capabilities_map",
            "summary": "Initialize\u0020CP\u0020roles\u0020capabilities\u0020list",
            "url": "../classes/cp-Config.html#method_init_capabilities_map"
        },                {
            "fqsen": "\\cp\\Config\u003A\u003Ainit_all_caps\u0028\u0029",
            "name": "init_all_caps",
            "summary": "Initialize\u0020CP\u0020custom\u0020capabilities",
            "url": "../classes/cp-Config.html#method_init_all_caps"
        },                {
            "fqsen": "\\cp\\Config\u003A\u003Ainit_permalink_options\u0028\u0029",
            "name": "init_permalink_options",
            "summary": "Initialize\u0020CP\u0020permalink\u0020options",
            "url": "../classes/cp-Config.html#method_init_permalink_options"
        },                {
            "fqsen": "\\cp\\Config\u003A\u003Ainit_predefined_pages\u0028\u0029",
            "name": "init_predefined_pages",
            "summary": "Initialize\u0020CP\u0020predefined\u0020pages",
            "url": "../classes/cp-Config.html#method_init_predefined_pages"
        },                {
            "fqsen": "\\cp\\Config\u003A\u003Ainit_email_notifications\u0028\u0029",
            "name": "init_email_notifications",
            "summary": "Initialize\u0020CP\u0020email\u0020notifications",
            "url": "../classes/cp-Config.html#method_init_email_notifications"
        },                {
            "fqsen": "\\cp\\Config\u003A\u003A\u0024defaults",
            "name": "defaults",
            "summary": "",
            "url": "../classes/cp-Config.html#property_defaults"
        },                {
            "fqsen": "\\cp\\Config\u003A\u003A\u0024custom_roles",
            "name": "custom_roles",
            "summary": "",
            "url": "../classes/cp-Config.html#property_custom_roles"
        },                {
            "fqsen": "\\cp\\Config\u003A\u003A\u0024all_caps",
            "name": "all_caps",
            "summary": "",
            "url": "../classes/cp-Config.html#property_all_caps"
        },                {
            "fqsen": "\\cp\\Config\u003A\u003A\u0024capabilities_map",
            "name": "capabilities_map",
            "summary": "",
            "url": "../classes/cp-Config.html#property_capabilities_map"
        },                {
            "fqsen": "\\cp\\Config\u003A\u003A\u0024permalink_options",
            "name": "permalink_options",
            "summary": "",
            "url": "../classes/cp-Config.html#property_permalink_options"
        },                {
            "fqsen": "\\cp\\Config\u003A\u003A\u0024predefined_pages",
            "name": "predefined_pages",
            "summary": "",
            "url": "../classes/cp-Config.html#property_predefined_pages"
        },                {
            "fqsen": "\\cp\\Config\u003A\u003A\u0024email_notifications",
            "name": "email_notifications",
            "summary": "",
            "url": "../classes/cp-Config.html#property_email_notifications"
        },                {
            "fqsen": "\\CP_Functions",
            "name": "CP_Functions",
            "summary": "Class\u0020CP_Functions",
            "url": "../classes/CP-Functions.html"
        },                {
            "fqsen": "\\CP_Functions\u003A\u003Ais_request\u0028\u0029",
            "name": "is_request",
            "summary": "What\u0020type\u0020of\u0020request\u0020is\u0020this\u003F",
            "url": "../classes/CP-Functions.html#method_is_request"
        },                {
            "fqsen": "\\CP_Functions\u003A\u003Adefine\u0028\u0029",
            "name": "define",
            "summary": "Define\u0020constant\u0020if\u0020not\u0020already\u0020set.",
            "url": "../classes/CP-Functions.html#method_define"
        },                {
            "fqsen": "\\CP_Functions\u003A\u003Aarray_insert_after\u0028\u0029",
            "name": "array_insert_after",
            "summary": "Easy\u0020merge\u0020arrays\u0020based\u0020on\u0020parent\u0020array\u0020key.\u0020Insert\u0020after\u0020selected\u0020key",
            "url": "../classes/CP-Functions.html#method_array_insert_after"
        },                {
            "fqsen": "\\CP_Functions\u003A\u003Ainit_current_locale\u0028\u0029",
            "name": "init_current_locale",
            "summary": "Init\u0020current\u0020locale\u0020if\u0020exists",
            "url": "../classes/CP-Functions.html#method_init_current_locale"
        },                {
            "fqsen": "\\CP_Functions\u003A\u003A\u0024is_permalinks",
            "name": "is_permalinks",
            "summary": "",
            "url": "../classes/CP-Functions.html#property_is_permalinks"
        },                {
            "fqsen": "\\CP_Functions\u003A\u003A\u0024scrips_prefix",
            "name": "scrips_prefix",
            "summary": "",
            "url": "../classes/CP-Functions.html#property_scrips_prefix"
        },                {
            "fqsen": "\\cp\\common\\Init",
            "name": "Init",
            "summary": "Class\u0020Init",
            "url": "../classes/cp-common-Init.html"
        },                {
            "fqsen": "\\cp\\common\\Init\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Init\u0020constructor.",
            "url": "../classes/cp-common-Init.html#method___construct"
        },                {
            "fqsen": "\\cp\\common\\Init\u003A\u003Aincludes\u0028\u0029",
            "name": "includes",
            "summary": "Common\u0020plugin\u0020includes",
            "url": "../classes/cp-common-Init.html#method_includes"
        },                {
            "fqsen": "\\cp\\common\\Init\u003A\u003Apermalinks\u0028\u0029",
            "name": "permalinks",
            "summary": "",
            "url": "../classes/cp-common-Init.html#method_permalinks"
        },                {
            "fqsen": "\\cp\\common\\Init\u003A\u003Arewrite\u0028\u0029",
            "name": "rewrite",
            "summary": "",
            "url": "../classes/cp-common-Init.html#method_rewrite"
        },                {
            "fqsen": "\\cp\\common\\Options",
            "name": "Options",
            "summary": "Class\u0020Options",
            "url": "../classes/cp-common-Options.html"
        },                {
            "fqsen": "\\cp\\common\\Options\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Options\u0020constructor.",
            "url": "../classes/cp-common-Options.html#method___construct"
        },                {
            "fqsen": "\\cp\\common\\Options\u003A\u003Aget_key\u0028\u0029",
            "name": "get_key",
            "summary": "Returns\u0020options\u0020key",
            "url": "../classes/cp-common-Options.html#method_get_key"
        },                {
            "fqsen": "\\cp\\common\\Options\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Get\u0020CPortal\u0020option\u0020value",
            "url": "../classes/cp-common-Options.html#method_get"
        },                {
            "fqsen": "\\cp\\common\\Options\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Add\u0020CPortal\u0020option\u0020value",
            "url": "../classes/cp-common-Options.html#method_add"
        },                {
            "fqsen": "\\cp\\common\\Options\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020CPortal\u0020option\u0020value",
            "url": "../classes/cp-common-Options.html#method_update"
        },                {
            "fqsen": "\\cp\\common\\Options\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Delete\u0020CPortal\u0020option",
            "url": "../classes/cp-common-Options.html#method_delete"
        },                {
            "fqsen": "\\cp\\common\\Options\u003A\u003Aget_default\u0028\u0029",
            "name": "get_default",
            "summary": "Get\u0020CPortal\u0020option\u0020default\u0020value",
            "url": "../classes/cp-common-Options.html#method_get_default"
        },                {
            "fqsen": "\\cp\\common\\Options\u003A\u003Aget_predefined_page_option_key\u0028\u0029",
            "name": "get_predefined_page_option_key",
            "summary": "Get\u0020predefined\u0020page\u0020option\u0020key",
            "url": "../classes/cp-common-Options.html#method_get_predefined_page_option_key"
        },                {
            "fqsen": "\\cp\\common\\Options\u003A\u003A\u0024options",
            "name": "options",
            "summary": "",
            "url": "../classes/cp-common-Options.html#property_options"
        },                {
            "fqsen": "\\cp\\common\\Permalinks",
            "name": "Permalinks",
            "summary": "Class\u0020Permalinks",
            "url": "../classes/cp-common-Permalinks.html"
        },                {
            "fqsen": "\\cp\\common\\Permalinks\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Permalinks\u0020constructor.",
            "url": "../classes/cp-common-Permalinks.html#method___construct"
        },                {
            "fqsen": "\\cp\\common\\Permalinks\u003A\u003Aget_slug\u0028\u0029",
            "name": "get_slug",
            "summary": "Get\u0020page\u0020slug",
            "url": "../classes/cp-common-Permalinks.html#method_get_slug"
        },                {
            "fqsen": "\\cp\\common\\Permalinks\u003A\u003Apredefined_page_slug_exists\u0028\u0029",
            "name": "predefined_page_slug_exists",
            "summary": "",
            "url": "../classes/cp-common-Permalinks.html#method_predefined_page_slug_exists"
        },                {
            "fqsen": "\\cp\\common\\Permalinks\u003A\u003Aget_predefined_page_id\u0028\u0029",
            "name": "get_predefined_page_id",
            "summary": "Get\u0020predefined\u0020page\u0020ID",
            "url": "../classes/cp-common-Permalinks.html#method_get_predefined_page_id"
        },                {
            "fqsen": "\\cp\\common\\Permalinks\u003A\u003Ais_predefined_page\u0028\u0029",
            "name": "is_predefined_page",
            "summary": "",
            "url": "../classes/cp-common-Permalinks.html#method_is_predefined_page"
        },                {
            "fqsen": "\\cp\\common\\Permalinks\u003A\u003Aget_predefined_page_link\u0028\u0029",
            "name": "get_predefined_page_link",
            "summary": "Get\u0020predefined\u0020page\u0020URL",
            "url": "../classes/cp-common-Permalinks.html#method_get_predefined_page_link"
        },                {
            "fqsen": "\\cp\\common\\Permalinks\u003A\u003Aare_pages_installed\u0028\u0029",
            "name": "are_pages_installed",
            "summary": "Are\u0020CP\u0020pages\u0020installed",
            "url": "../classes/cp-common-Permalinks.html#method_are_pages_installed"
        },                {
            "fqsen": "\\cp\\common\\Rewrite",
            "name": "Rewrite",
            "summary": "Class\u0020Rewrite",
            "url": "../classes/cp-common-Rewrite.html"
        },                {
            "fqsen": "\\cp\\common\\Rewrite\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Rewrite\u0020constructor.",
            "url": "../classes/cp-common-Rewrite.html#method___construct"
        },                {
            "fqsen": "\\cp\\common\\Rewrite\u003A\u003Ainit_variables\u0028\u0029",
            "name": "init_variables",
            "summary": "Init\u0020variables\u0020for\u0020permalinks",
            "url": "../classes/cp-common-Rewrite.html#method_init_variables"
        },                {
            "fqsen": "\\cp\\common\\Rewrite\u003A\u003Areset_rules\u0028\u0029",
            "name": "reset_rules",
            "summary": "Update\u0020\u0022flush\u0022\u0020option\u0020for\u0020reset\u0020rules\u0020on\u0020wp_loaded\u0020hook",
            "url": "../classes/cp-common-Rewrite.html#method_reset_rules"
        },                {
            "fqsen": "\\cp\\common\\Rewrite\u003A\u003Amaybe_flush_rewrite_rules\u0028\u0029",
            "name": "maybe_flush_rewrite_rules",
            "summary": "Reset\u0020Rewrite\u0020rules\u0020if\u0020need\u0020it.",
            "url": "../classes/cp-common-Rewrite.html#method_maybe_flush_rewrite_rules"
        },                {
            "fqsen": "\\cp\\frontend\\Init",
            "name": "Init",
            "summary": "Class\u0020Init",
            "url": "../classes/cp-frontend-Init.html"
        },                {
            "fqsen": "\\cp\\frontend\\Init\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Init\u0020constructor.",
            "url": "../classes/cp-frontend-Init.html#method___construct"
        },                {
            "fqsen": "\\cp\\frontend\\Init\u003A\u003Aincludes\u0028\u0029",
            "name": "includes",
            "summary": "",
            "url": "../classes/cp-frontend-Init.html#method_includes"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "../namespaces/default.html"
        },                {
            "fqsen": "\\cp\\admin",
            "name": "admin",
            "summary": "",
            "url": "../namespaces/cp-admin.html"
        },                {
            "fqsen": "\\cp\\ajax",
            "name": "ajax",
            "summary": "",
            "url": "../namespaces/cp-ajax.html"
        },                {
            "fqsen": "\\cp",
            "name": "cp",
            "summary": "",
            "url": "../namespaces/cp.html"
        },                {
            "fqsen": "\\cp\\common",
            "name": "common",
            "summary": "",
            "url": "../namespaces/cp-common.html"
        },                {
            "fqsen": "\\cp\\frontend",
            "name": "frontend",
            "summary": "",
            "url": "../namespaces/cp-frontend.html"
        }            ]
);
